services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - 5432:5432
